# Generated by Django 2.1.4 on 2019-02-12 10:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_name', models.CharField(max_length=64)),
                ('ip', models.CharField(max_length=32)),
                ('host_status', models.IntegerField(choices=[(0, '正常'), (1, '不可达')], default=1)),
                ('assets_stauts', models.IntegerField(choices=[(0, '在线'), (1, '测试'), (2, '闲置'), (3, '保修')])),
                ('opm_name', models.CharField(max_length=32)),
                ('idc', models.CharField(max_length=64)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('remark', models.CharField(max_length=128)),
            ],
        ),
    ]
