# Generated by Django 2.1.4 on 2019-02-13 16:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hosts', models.TextField()),
                ('module', models.CharField(max_length=32)),
                ('option', models.CharField(max_length=128)),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
