# Generated by Django 2.1.4 on 2019-02-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cmdb', '0003_record_result'),
    ]

    operations = [
        migrations.RenameField(
            model_name='record',
            old_name='option',
            new_name='module_args',
        ),
    ]
